import { useEffect, useState } from 'react';

/**
 * AIResponseCard Component
 * Displays AI-generated responses with typing animation and glow effects
 * 
 * Props:
 * - response: string | AI response text
 * - isLoading: boolean | Show typing animation
 * - question: string | The question that was asked
 */
const AIResponseCard = ({ response, isLoading, question }) => {
  const [displayedText, setDisplayedText] = useState('');

  // Typing animation effect
  useEffect(() => {
    if (!isLoading && response) {
      let index = 0;
      setDisplayedText('');
      
      const typingInterval = setInterval(() => {
        if (index < response.length) {
          setDisplayedText(response.substring(0, index + 1));
          index++;
        } else {
          clearInterval(typingInterval);
        }
      }, 20); // Speed of typing

      return () => clearInterval(typingInterval);
    }
  }, [response, isLoading]);

  return (
    <div className="glow-card animate-fade-in mb-6 max-w-2xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-3 mb-4">
        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center">
          <span className="text-white font-bold">✨</span>
        </div>
        <h3 className="neon-text font-semibold">AI Response</h3>
      </div>

      {/* Question display */}
      {question && (
        <div className="mb-4 p-3 bg-white/5 rounded-lg border border-white/10">
          <p className="text-xs text-primary-400 uppercase tracking-wider font-semibold">Your Question</p>
          <p className="text-white/90 mt-1">{question}</p>
        </div>
      )}

      {/* Loading state with typing animation */}
      {isLoading && (
        <div className="flex items-center gap-2">
          <span className="text-white/70">Thinking</span>
          <span className="flex gap-1">
            <span className="w-2 h-2 bg-primary-500 rounded-full animate-bounce" style={{ animationDelay: '0s' }} />
            <span className="w-2 h-2 bg-primary-500 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} />
            <span className="w-2 h-2 bg-primary-500 rounded-full animate-bounce" style={{ animationDelay: '0.4s' }} />
          </span>
        </div>
      )}

      {/* Response text with typing animation */}
      {!isLoading && response && (
        <div className="space-y-3">
          <p className="text-white/90 leading-relaxed text-sm md:text-base whitespace-pre-wrap">
            {displayedText}
            {displayedText.length < response.length && (
              <span className="inline-block w-2 h-4 ml-1 bg-primary-500 animate-pulse" />
            )}
          </p>
        </div>
      )}

      {/* Footer with timestamp */}
      {!isLoading && response && (
        <div className="mt-4 pt-4 border-t border-white/10">
          <p className="text-xs text-white/40">
            Generated by AI • {new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>
      )}
    </div>
  );
};

export default AIResponseCard;
